svn export svn://xxxche.wicp.net/jobs/frontend/web/css/m/main.css /alidata/www/jobs/frontend/web/css/m/main.css
svn export svn://xxxche.wicp.net/jobs/frontend/web/css/m/search.css /alidata/www/jobs/frontend/web/css/m/search.css
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/search_home.html /alidata/www/jobs/frontend/web/template/search_home.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/search_industries.html /alidata/www/jobs/frontend/web/template/search_industries.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/search_salary.html /alidata/www/jobs/frontend/web/template/search_salary.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/search_locations.html /alidata/www/jobs/frontend/web/template/search_locations.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/list_block.html /alidata/www/jobs/frontend/web/template/list_block.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/selection_nav.html /alidata/www/jobs/frontend/web/template/selection_nav.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/search_term.html /alidata/www/jobs/frontend/web/template/search_term.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/search_level.html /alidata/www/jobs/frontend/web/template/search_level.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/search_functions.html /alidata/www/jobs/frontend/web/template/search_functions.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/functions_selections.html /alidata/www/jobs/frontend/web/template/functions_selections.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/search_education.html /alidata/www/jobs/frontend/web/template/search_education.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/template/list.html /alidata/www/jobs/frontend/web/template/list.html
svn export svn://xxxche.wicp.net/jobs/frontend/web/js/m/main.js /alidata/www/jobs/frontend/web/js/m/main.js
svn export svn://xxxche.wicp.net/jobs/frontend/web/js/m/main.js.map /alidata/www/jobs/frontend/web/js/m/main.js.map
svn export svn://xxxche.wicp.net/jobs/frontend/web/js/jquery-touch/touch-event.js /alidata/www/jobs/frontend/web/js/jquery-touch/touch-event.js
svn export svn://xxxche.wicp.net/jobs/frontend/web/index.php /alidata/www/jobs/frontend/web/index.php
svn export svn://xxxche.wicp.net/jobs/scripts/svn.sh /alidata/www/jobs/scripts/svn.sh
svn export svn://xxxche.wicp.net/jobs/common/components/collecter/Jobsdb.php /alidata/www/jobs/common/components/collecter/Jobsdb.php
svn export svn://xxxche.wicp.net/jobs/common/config/record-total.txt /alidata/www/jobs/common/config/record-total.txt
svn export svn://xxxche.wicp.net/jobs/common/base/Collecter.php /alidata/www/jobs/common/base/Collecter.php
svn export svn://xxxche.wicp.net/jobs/common/function.php /alidata/www/jobs/common/function.php
svn export svn://xxxche.wicp.net/jobs/vendor/modules/mobile/views/default/layout.twig /alidata/www/jobs/vendor/modules/mobile/views/default/layout.twig
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/css/m/main.css /alidata/www/jobs/jobsApp/www/css/m/main.css
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/css/m/search.css /alidata/www/jobs/jobsApp/www/css/m/search.css
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/search_home.html /alidata/www/jobs/jobsApp/www/template/search_home.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/search_industries.html /alidata/www/jobs/jobsApp/www/template/search_industries.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/search_locations.html /alidata/www/jobs/jobsApp/www/template/search_locations.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/search_salary.html /alidata/www/jobs/jobsApp/www/template/search_salary.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/list_block.html /alidata/www/jobs/jobsApp/www/template/list_block.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/selection_nav.html /alidata/www/jobs/jobsApp/www/template/selection_nav.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/search_level.html /alidata/www/jobs/jobsApp/www/template/search_level.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/search_term.html /alidata/www/jobs/jobsApp/www/template/search_term.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/search_functions.html /alidata/www/jobs/jobsApp/www/template/search_functions.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/functions_selections.html /alidata/www/jobs/jobsApp/www/template/functions_selections.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/search_education.html /alidata/www/jobs/jobsApp/www/template/search_education.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/template/list.html /alidata/www/jobs/jobsApp/www/template/list.html
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/js/m/main.js /alidata/www/jobs/jobsApp/www/js/m/main.js
svn export svn://xxxche.wicp.net/jobs/jobsApp/www/js/m/main.js.map /alidata/www/jobs/jobsApp/www/js/m/main.js.map
svn export svn://xxxche.wicp.net/jobs/console/config/main.php /alidata/www/jobs/console/config/main.php
svn export svn://xxxche.wicp.net/jobs/console/controllers/CollectController.php /alidata/www/jobs/console/controllers/CollectController.php
svn export svn://xxxche.wicp.net/jobs/console/controllers/NewExeception.php /alidata/www/jobs/console/controllers/NewExeception.php
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/less/m/main.less /alidata/www/jobs/frontFramework/assets/less/m/main.less
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/less/m/search.less /alidata/www/jobs/frontFramework/assets/less/m/search.less
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/search_home.html /alidata/www/jobs/frontFramework/assets/template/search_home.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/search_industries.html /alidata/www/jobs/frontFramework/assets/template/search_industries.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/search_locations.html /alidata/www/jobs/frontFramework/assets/template/search_locations.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/search_salary.html /alidata/www/jobs/frontFramework/assets/template/search_salary.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/list_block.html /alidata/www/jobs/frontFramework/assets/template/list_block.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/selection_nav.html /alidata/www/jobs/frontFramework/assets/template/selection_nav.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/search_level.html /alidata/www/jobs/frontFramework/assets/template/search_level.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/search_term.html /alidata/www/jobs/frontFramework/assets/template/search_term.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/search_functions.html /alidata/www/jobs/frontFramework/assets/template/search_functions.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/functions_selections.html /alidata/www/jobs/frontFramework/assets/template/functions_selections.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/search_education.html /alidata/www/jobs/frontFramework/assets/template/search_education.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/template/list.html /alidata/www/jobs/frontFramework/assets/template/list.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/assets/js/m/main.js /alidata/www/jobs/frontFramework/assets/js/m/main.js
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/search_home.html /alidata/www/jobs/frontFramework/public/template/search_home.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/search_industries.html /alidata/www/jobs/frontFramework/public/template/search_industries.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/search_salary.html /alidata/www/jobs/frontFramework/public/template/search_salary.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/search_locations.html /alidata/www/jobs/frontFramework/public/template/search_locations.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/list_block.html /alidata/www/jobs/frontFramework/public/template/list_block.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/selection_nav.html /alidata/www/jobs/frontFramework/public/template/selection_nav.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/search_term.html /alidata/www/jobs/frontFramework/public/template/search_term.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/search_level.html /alidata/www/jobs/frontFramework/public/template/search_level.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/search_functions.html /alidata/www/jobs/frontFramework/public/template/search_functions.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/functions_selections.html /alidata/www/jobs/frontFramework/public/template/functions_selections.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/search_education.html /alidata/www/jobs/frontFramework/public/template/search_education.html
svn export svn://xxxche.wicp.net/jobs/frontFramework/public/template/list.html /alidata/www/jobs/frontFramework/public/template/list.html
